### PR TITLE
Change GitHub URL in repo manifest

### PR DESCRIPTION
**Pull request by G-ESmart**

### CODE REVIEW

**Comment by ajasmin** [comment]
We were having trouble cloning with the repo `git://github.com/phytec`. I believe this uses the unencrypted git protocol, which GitHub no longer supports.

This PR changes the scheme to `https`. Same as for `https://github.com/nxp/` which appears in the same manifest file.

**Comment by dominiknh90** [comment]
Thanks! Yes, we need the https protocol there.

Can you add a Signed-off-by: to your commit?

**Comment by G-ESmart** [comment]
My commit has been Signed-off

**Comment by smk-embedded** [comment]
merged

**Pull request closed without merging**
